### ISSUE TITLE
How can I access global variables within Vue components?

### ISSUE THREAD

**Issue by sw00d** [nuxt-community/style-resources-module#125]
Everything is working great with the package thus far. I have a stylus file holding my global variables and can access them in .vue files, as expected. I'm wondering if there is any way to access these variables within Vue components, inline-like. 

For example: 

Variable Defintion:
```styl
// style.styl
...
$yellow ?= #fad569
...
```

This works:
```vue
<!-- my-component.vue -->
...
<style lang="stylus" scoped>
   .myClass
       color $yellow
</style>
```

This does not work (Vuetify is being used here):
```vue
<!-- my-component.vue --> 
<v-tabs slider-color="$yellow" slider-size="4">
    ...
</v-tabs>
```

Is there any way currently to do this?

**Comment by jaythomas** [comment]
There is no way currently to do this. I'm not sure how feasible the feature would be given you'd need to do preprocessing on the templates to substitute in the correct value. Perhaps a maintainer of this project can speak better to that.

For what it's worth, you can fetch CSS3 variables from javascript during runtime: https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties#Values_in_JavaScript

If giving up stylus isn't feasible, you may want to even consider parsing the variables out of your "variables" style file and injecting them with webpack via the [DefinePlugin](https://webpack.js.org/plugins/define-plugin/). A bit hackish and boilerplate-y but that's all I got off the top of my head.

**Comment by rchl** [comment]
This feature request would be very hard to implement and I would argue that this module is not really the right place to do it.

It would be better done on some different level so that it works regardless whether this module is used or not. For example it should work also when defining a variable in the `style` block itself.
