### ISSUE TITLE
SVG doesnt work when Im using SASS in VUE compontent throw with style-resources-module

### ISSUE THREAD

**Issue by rafalradomski** [nuxt-community/style-resources-module#130]
Any idea how to get that working in nuxt.js?

```
<script>component logic...</script>
<style lang="scss">
.test {
    background-image: url('~assets/icons/check-mark.svg'); <-- doesnt work
}
</style>
```

It's returning [Object object] instead of the SVG icon

**Comment by rchl** [comment]
This issue is unrelated to this module.

That said, that syntax should work. Please ask on Nuxt Discord if you still have this issue.
