### ISSUE TITLE
Add whitespace under README.md title

### ISSUE THREAD

**Issue by joelworsham** [nuxt-community/style-resources-module#14]
I know I know, this seems so silly, but my IDE (webstorm) auto-pulls this when hovering `package.json` and it pulls in all of the `[![npm...` stuff.

Here's a weird GIF of it:
https://d.pr/i/dXl432

**Comment by manniL** [comment]
Done, thanks! 👍 
https://github.com/nuxt-community/style-resources-module/commit/df29cbbbac54b70096bf404d3ec239f561449f14
