### ISSUE TITLE
This dependency was not found 

### ISSUE THREAD

**Issue by kayw-geek** [nuxt-community/style-resources-module#142]
Before, I used the package "nuxt sass resources loader" alone, which later led to sass errors. When I used the package "@ nuxtjs / style resources", when I created a new page and new code, he prompted me that there was something wrong with the image path. Can you help me? I have been troubled for two or three days. Thank you very much.

My Code:
`<style lang="scss" scoped>
    .overview-m2-pro{ 
        width: 750px;
        background: #020E24;
        .m2-pro-desc{
            height: 1199px;
            width: 750px;
            background: url("~assets/images/m2pro/#1-img_1@2x.png") center center no-repeat;
        }
        .m2-pro-desc-card{
            margin-top: 140px;
            margin-left:50px;
        }
    }
</style>`

Error:
```Failed to compile with 1 errors                                                                                                                             friendly-errors 17:21:55  

This dependency was not found:                                                                                                                                      friendly-errors 17:21:55
                                                                                                                                                                    friendly-errors 17:21:55
* assets/images/m2pro/ in ./node_modules/css-loader/dist/cjs.js??ref--7-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--7-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js??ref--7-oneOf-1-3!./node_modules/sass-resources-loader/lib/loader.js??ref--7-oneOf-1-4!./node_modules/@nuxt/components/dist/loader.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./components/base/detail/OverviewM2pro.vue?vue&type=style&index=0&id=5cbc17b8&lang=scss&scoped=true&
```

Nuxt version v2.14.8

nuxt.config,js
```
modules: [
    '@nuxtjs/axios',
    ['@nuxtjs/pwa', {
      icon: false
    }],
    'nuxt-clipboard2',
    '@blokwise/dynamic',
    'nuxt-sass-resources-loader'
    ],
  buildModules:[
    '@nuxtjs/style-resources',
  ],
  styleResources: {
    scss: [
      '~/assets/sass/resource.scss'
      ]
  },
```
package.json

```
"devDependencies": {
    "@nuxtjs/style-resources": "^1.0.0",
    "node-sass": "^4.14.1",
    "sass": "^1.32.5",
    "sass-loader": "^7.3.1",
    "sass-resources-loader": "^2.1.1"
  },

"dependencies":{
 "nuxt-sass-resources-loader": "^2.0.5",
}
```

**Comment by rchl** [comment]
This module and `nuxt-sass-resources-loader` seem like they kinda do the same so try removing `nuxt-sass-resources-loader`.

Also, I'm not sure what will understand the URL format like `~assets/images/m2pro/#1-img_1@2x.png`. If it's one of your other modules that parses that then you might want to tweak the order of modules. Put all those modules in `modules` array (even if it's not recommended) and make sure that `@nuxtjs/style-resources` is last in the list.

**Comment by kayw-geek** [comment]
> This module and `nuxt-sass-resources-loader` seem like they kinda do the same so try removing `nuxt-sass-resources-loader`.
> 
> Also, I'm not sure what will understand the URL format like `~assets/images/m2pro/#1-img_1@2x.png`. If it's one of your other modules that parses that then you might want to tweak the order of modules. Put all those modules in the `modules` array (even if it's not recommended) and make sure that `@nuxtjs/style-resources` is last in the list.

I've solved it because the picture name starts with #.
