### ISSUE TITLE
Unable to use Sass built-in modules

### ISSUE THREAD

**Issue by markhorgan** [nuxt-community/style-resources-module#143]
I'm using dart-sass node module but stylesheets loaded with the style resources module aren't able to load Sass built-in modules

E.g.

abstractions/units.scss:

`@use "sass:math";`

nuxt.config.js:

```
styleResources: {
  scss: [
    '~/assets/scss/abstractions/*.scss',
    ]
  },

  css: [
    '~/assets/scss/global.scss'
  ],
```
Results in the error: 

SassError: Invalid Sass identifier "sass:math"
@use "abstractions/sass:math";

If I exclude the file from being loaded by style resources module and import it manually from my `global.scss` file it seems to work ok.

**Comment by koleburg** [comment]
Works only if specified in the tag style

`
<style lang="scss" scoped>
@use "sass:map";
.test {
  @include theme(
      (
          "color": "primary",
          "background-color": "success"
      )
  )
}
</style>`

**Comment by leevihuhtamaa** [comment]
I can confirm this issue and looking for a solutions :(

**Comment by leevihuhtamaa** [comment]
> If I exclude the file from being loaded by style resources module and import it manually from my `global.scss` file it seems to work ok.

@markhorgan how did you get this working? if i declare @use 'sass:math'; in my 'global.scss' i get following error: `SassError: @use rules must be written before any other rules.`

Or did you just dropped styleResources completely in this scenario?

**Comment by webistomin** [comment]
Same here. Any solutions?

**Comment by dcrabbeYapily** [comment]
any solution to this would be great.
```SassError: Invalid Sass identifier "sass:math"
  ╷
2 │ @use '../assets/styles/sass:math';
```

**Comment by ehainer** [comment]
Probably not the most ideal solution to this problem (smarter and more patient minds than I could jump in), but I managed to get this working by adding the following to my nuxt.config.js:

```build: {
  extend(config, { loaders }){
    loaders.scss.additionalData = '@use "sass:math";'
  }
}```

I could then use `math.*` functions inside any *.scss file loaded from styleResources. Adjust your loader as necessary...

I would be curious to know what the drawbacks to this method are, either in terms of testing/compilation time and/or app size, if any.

**Comment by lada** [comment]
Have the same problem. Unfortunately the solution proposed by @ehainer does not work for me. Any other idea how to solve it would be really welcome.

**Comment by andrey-hohlov** [comment]
https://www.npmjs.com/package/style-resources-loader for example has ```hoistUseStatements``` options to handle this case

**Comment by rchl** [comment]
👍

**Comment by rchl** [comment]
Support for that was added in v1.1.0 through https://github.com/nuxt-community/style-resources-module/pull/162

**Comment by botteu** [comment]
I cannot get this to work. Either I get `SassError: @use rules must be written before any other rules.` or when I use `hoistUseStatements: true` I get errors like `SassError: Invalid Sass identifier "sass:math"` because the @use-statements come out like `@use '../../../assets/styles/config/sass:math';`.
I feel like I've tried everthing...

**Comment by rchl** [comment]
Create a reproduction repo and someone will probably be able to help you.

**Comment by leevihuhtamaa** [comment]
> Support for that was added in v1.1.0 through #162

Thanks @rchl ! Works like a charm

**Comment by riddla** [comment]
@rchl, @botteu: I could re-create it in https://codesandbox.io/s/nuxtjsstyle-resources-hoistusestatements-forked-p4ct3?file=/nuxt.config.js:78-107.

**Comment by rchl** [comment]
@riddla try removing `yarn.lock` and `node_modules` and re-run `yarn`.

**Comment by Alphability** [comment]
> @riddla try removing `yarn.lock` and `node_modules` and re-run `yarn`.

Having the same problem. Removing `yarn.lock` and `node_modules` didn't resolve the issue.

**Comment by Alphability** [comment]
@riddla did you found a hack for this?

**Comment by Alphability** [comment]
Having only one file using `@use`and `@forward`statements seems to work.

The problem comes when I import multiple files that use `@use` or `@forward`. Even when using `hoistUseStatements: true`.

**Comment by rchl** [comment]
Please create reproduction

**Comment by Alphability** [comment]
I'm not able to create a reproduction. Codesandbox is shit.

With the Nuxt's codesandbox template I'm not even able to use `lang="scss"` in a component... "sass-loader not found in /sandbox" even after installing it 😂

I don't have time to battle with a fake environment.

What I can tell you is that I use:
- "@nuxtjs/style-resources": "^1.2.0",
- "nuxt": "^2.15.0"
- "sass": "^1.35.2",

**Comment by rchl** [comment]
You can create a repo locally and push it to GitHub

**Comment by Alphability** [comment]
Dude I don't have time to create a repo, and push it to GitHub to help you debug.
I'm already working on a personal projet on a Sunday. I'm not here to become a collaborator on style-resources.

You wanna reproduce :
1. `create-nuxt-app`
2. install `@nuxtjs/style-resources` and `sass`
3. create multiple scss files
4. use `hoistUseStatements: true`
5. in all those files use `sass:string`, `sass:map`, etc. and create dummy functions (at least one @use per file)
6. run your Nuxt app
7. debug

**Comment by rchl** [comment]
You have an issue and not me so sorry but i won't spend time trying to reproduce it if you don't even care enough to create a straightforward reproduction.

Even og there is an issue, it likely it's the sass-loader itself, to be fair.

**Comment by riddla** [comment]
@rchl What about the two reproductions on CodeSandbox that I posted above?
(Removing yarn.lock and node_modules did also not do the trick for me locally.)

**Comment by rchl** [comment]
> @rchl What about the two reproductions on CodeSandbox that I posted above?
> (Removing yarn.lock and node_modules did also not do the trick for me locally.)

It did help here when I've tried it

**Comment by Alphability** [comment]
> You have an issue and not me so sorry but i won't spend time trying to reproduce it if you don't even care enough to create a straightforward reproduction.
> 
> Even if there is an issue, it likely is in the sass-loader itself, to be fair.

Here I created a repo @rchl.

**Comment by rchl** [comment]
Might be some case that is not handled by `sass-resources-loader` but what you could do is create a small SCSS wrapper file like `app.scss` with

```scss
@import 'constants';
@import 'functions';
@import 'mixins';
```

and import that instead.

**Comment by Alphability** [comment]
> Might be some case that is not handled by `sass-resources-loader` but what you could do is create a small SCSS wrapper file like `app.scss` with
> 
> ```css-scss
> @import 'constants';
> @import 'functions';
> @import 'mixins';
> ```
> 
> and import that instead.

It seems to be working with on file importing (w/ `@import`) all the other files I wanted to use w/ style-resources.
In the imported files I can use `@use` rules.

Thanks @rchl!

**Comment by mahish** [comment]
Temporary fix https://github.com/shakacode/sass-resources-loader/issues/148

**Comment by rchl** [comment]
Using single quotes instead of double quotes doesn't fix the reproduction above. At least not fully, so there is likely another issues in the loader.

Feel free to report an issue there if it's important for you.

**Comment by Asef00** [comment]
In my case fixed by:

- Using `hoistUseStatements: true`
- Wrapping all resources(variables & mixins) into a single SCSS file with `@use 'sass:math';` in first line.
