### ISSUE TITLE
 Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by Bokhanchenko** [nuxt-community/style-resources-module#168]
Hello! I have an error after reinstall npm packages. I remove "node_modules" and "package-lock.json", after "npm i" and "npm run dev". I have an error - "can read property indexOf of undefined".

![image](https://user-images.githubusercontent.com/14982020/122554670-f95ceb00-d041-11eb-94b4-e3f731d05ee3.png)
![image](https://user-images.githubusercontent.com/14982020/122554780-15f92300-d042-11eb-8409-69772971db3b.png)
![image](https://user-images.githubusercontent.com/14982020/122554832-24dfd580-d042-11eb-845b-4849b99c075e.png)

**Comment by Bokhanchenko** [comment]
I see difference in "package_lock.json"
NEW:
![image](https://user-images.githubusercontent.com/14982020/122556365-15618c00-d044-11eb-9fb0-e0b62b064f34.png)
OLD:
![image](https://user-images.githubusercontent.com/14982020/122556395-1b576d00-d044-11eb-9e61-4cc6b52c8826.png)

**Comment by Bokhanchenko** [comment]
To fix this issue I use "npm i sass-resources-loader@2.1.1", but I think it will be better to update the package version in this library

**Comment by rchl** [comment]
No, we need the new version. There is something else in your project that is incompatible. Possibly the `sass-loader`. Try using version 10.

**Comment by CyberPunk10** [comment]
![image](https://user-images.githubusercontent.com/59876378/122605532-3fd13a80-d080-11eb-8900-a160b934749b.png)

How to fix it?

**Comment by rchl** [comment]
Actually that seems to indeed be a bug in `sass-resources-loader` 2.2.2. You can force 2.2.1 instead for the time being.

https://github.com/shakacode/sass-resources-loader/issues/144

**Comment by Bokhanchenko** [comment]
"sass-resources-loader": "2.2.1" - it helps

**Comment by rchl** [comment]
also published v1.2.0 that bumps `sass-resources-loader` to v2.2.3
