### ISSUE TITLE
SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by laariiane** [nuxt-community/style-resources-module#169]
Hello, I don't manage to get rid of this error : 

Error: /node_modules/@nuxtjs/style-resources/lib/module.js:5
  export default function nuxtStyledResources(moduleOptions) {
  ^^^^^^
  SyntaxError: Unexpected token 'export'

Each time I try npm run dev 

Nuxt.config 

`  
  css: [
    { src: '@/assets/styles/main.scss', lang: 'scss' }
  ],
  
  modules: [
    '@nuxtjs/style-resources',
  ],

  styleResources: {
    scss: ['@/assets/styles/utils/variables.scss']
  },`

"@nuxtjs/style-resources": "^1.1.0",

Do you have any idea ? Thank you !

**Comment by rchl** [comment]
Deleting `node_modules` and re-running npm or yarn install should help.

**Comment by laariiane** [comment]
I started from this repo : [](https://github.com/cosmicjs/vue-ecommerce?ref=hackernoon.com)
and I just added style-resources to it. 

Here is the package.json if I don't change anything except adding style-ressources : 

{
  "name": "cosmic-vuecommerce",
  "version": "1.0.0",
  "description": "E-commerce app with Nuxt and CosmicJS",
  "author": "Muhammad Althaf",
  "private": true,
  "scripts": {
    "dev": "cross-env NODE_ENV=development nodemon server/index.js --watch server",
    "build": "nuxt build",
    "start": "npm run build; cross-env NODE_ENV=production HOST=0.0.0.0 node server/index.js",
    "generate": "nuxt generate",
    "lint": "eslint --ext .js,.vue --ignore-path .gitignore .",
    "precommit": "npm run lint",
    "heroku-postbuild": "npm install --only=dev --no-shrinkwrap && npm run build"
  },
  "dependencies": {
    "@nuxtjs/axios": "^5.0.0",
    "@nuxtjs/style-resources": "^1.1.0",
    "babel": "^6.23.0",
    "babel-eslint": "^8.2.1",
    "body-parser": "^1.18.2",
    "buefy": "^0.6.3",
    "cosmicjs": "^3.0.9",
    "cross-env": "^5.0.1",
    "dotenv": "^5.0.0",
    "eslint": "^4.15.0",
    "eslint-loader": "^1.7.1",
    "eslint-plugin-vue": "^4.0.0",
    "express": "^4.15.3",
    "node-sass": "^4.7.2",
    "nodemon": "^1.11.0",
    "nuxt": "^1.0.0",
    "sass-loader": "^6.0.6",
    "stripe": "^5.4.0",
    "vue-stripe-checkout": "0.0.4"
  }
}

Thank you !

**Comment by rchl** [comment]
That repo is using Nuxt 1.x. Don't use such old versions.

**Comment by laariiane** [comment]
That was it ! Thank you ! I updated Nuxt and now it works perfectly.
