### ISSUE TITLE
nuxt SCSS can not use liner gradient on production

### ISSUE THREAD

**Issue by 1shaked** [nuxt-community/style-resources-module#173]
So I have a vue file which uses SCSS style (in all my project I am using SCSS) and from some reason when I use the 
` background-image: linear-gradient(to inline-start, $color-blue--navy 19934%, $color-blue--ocean 20002%) `
I get errors only when I run `npm build`; when I run dev, the app works fine. 
The Isueue is at  postcss-minify-gradients -> dist - > index.js 
![Screen Shot 2021-07-11 at 9 32 43](https://user-images.githubusercontent.com/40497915/125185044-f3b28980-e22a-11eb-9a17-d48e483925a9.png)

**Comment by rchl** [comment]
Are you able to create a project that reproduces this issue?

Also, try deleting the lock file and `node_modules` first and see if it still reproduces.

**Comment by rchl** [comment]
Closing due to no response.
Though I suppose this is not related to this module at all.
