### ISSUE TITLE
Module @nuxtjs/style-resources not found. How to use devDependencies on production?

### ISSUE THREAD

**Issue by dkoprowski** [nuxt-community/style-resources-module#184]
Hello,
I try to build my pages using `yarn generate` on production. I have the `NODE_ENV` flag set to `production` to not install all the dev dependencies. This package is required though to generate pages.

I don't want to set `NODE_ENV` to `dev` as it will install all the packages in `devDependencies` – which is a lot. 

I don't want to add this package to `dependencies` as well as it will generate a bundle with a package that is not needed for my users.

What do you do in those scenarios? Do you just always use `dev` mode even on production? What if you have some blocks of code inside your project that runs only on a `prod` environment? I think there should be some solution which I don't see.

Console output for future search:
> WARN  Module @nuxtjs/style-resources not found. Please ensure @nuxtjs/style-resources is in devDependencies and installed. HINT: During build step, for npm/yarn, NODE_ENV=production or --production should NOT be used.                      14:09:48

```
 ✖ Nuxt Fatal Error                                                                                                    │
   │                                                                                                                         │
   │   Error: Cannot find module '@nuxtjs/style-resources'  
```

**Comment by rchl** [comment]
Your current flow sounds a bit strange.

You should be generating your pages in a dev environment (on CI or whatever you use) and creating a package from that that you then deploy to production.

Alternatively just add this package to production dependencies. It won't affect what ends up in the resulting Nuxt bundle because that's not defined by whether dependency is a production dependency or not.

**Comment by dkoprowski** [comment]
Thank you @rchl. I assumed that everything that goes into `dependencies` goes to the bundle. 

How Nuxt knows which packages are production dependencies then?

**Comment by rchl** [comment]
I guess a simplified answer would be: it includes whatever is referenced from nuxt.config.js in one way or another (including through plugins added by modules).
