### ISSUE TITLE
nuxt3: resolver.resolveModule is not a function

### ISSUE THREAD

**Issue by Zielgestalt** [nuxt-community/style-resources-module#190]
Thanks for this module. It makes life so much easier! I tried to use it in with nuxt3 beta, but (as expected) it's not working out of the box. Is there a plan to make this module nuxt3 ready? Thanks!

Here's what I get when using it with sass and sass-loader:

Fresh nuxt3 beta install (3.0.0-27235451.ece0e01)

Mac OSX
Node: v14.17.6

yarn dev -o

Cannot start nuxt:  resolver.resolveModule is not a function

  at node_modules/@nuxtjs/style-resources/lib/module.js:35:43
  at Array.reduce (<anonymous>)
  at node_modules/@nuxtjs/style-resources/lib/module.js:34:42
  at Array.reduce (<anonymous>)
  at retrieveStyleArrays (node_modules/@nuxtjs/style-resources/lib/module.js:32:25)
  at Object.nuxtStyledResources (node_modules/@nuxtjs/style-resources/lib/module.js:50:60)
  at installModule (node_modules/@nuxt/kit/dist/index.mjs:1196:17)
  at initNuxt (node_modules/nuxt3/dist/index.mjs:817:11)
  at async load (node_modules/nuxi/dist/chunks/dev.mjs:6763:9)
  at async Object.invoke (node_modules/nuxi/dist/chunks/dev.mjs:6794:5)

✔ Generated nuxt.d.ts

**Comment by cheapwebmonkey** [comment]
same here

**Comment by designbydc** [comment]
With Nuxt 3 this module still is not supported. Use the `vite` config property with `preprocessorOptions` option:

```
vite: {
    css: {
        preprocessorOptions: {
            scss: {
                additionalData: '@import "@/assets/scss/global.scss";',
            },
        },
    },
}
```

Source: https://vite.nuxtjs.org/misc/common-issues#styleresources

**Comment by JonesGladston** [comment]
@designbydc Thanks, it works.

**Comment by henrycunh** [comment]
you can also pass the file path directly to the `css` option on the `nuxt.config.ts` file!

```ts
{
    css: [
        '@/assets/style/main.scss'
    ]
}
```

[reference](https://v3.nuxtjs.org/docs/directory-structure/nuxt.config#css)

**Comment by volkipp** [comment]
For anyone using webpack with Nuxt 3 or Nuxt Bridge, I was able to modify the plugin to use [@nuxt/kit](https://v3.nuxtjs.org/guide/going-further/kit#nuxt-kit). I don't have the bandwidth to formalize this as a pull request, but I did make a gist with some directions on how to install it. The good news is that I was able to test it using both Nuxt 3 and Nuxt Bridge and everything appears to work without a hitch.

https://gist.github.com/volkipp/56655a3743bd7ebab57a6666833f3ec2

With a little effort you should also be able to make this module add to the vite preprocessorOptions  as well.  Hopefully someone here can use this as a foundation to make a formal merge request.

Cheers! 🍻

**Comment by inomata137** [comment]
I had the same issue.
I wanted to use [sass-mq](https://www.npmjs.com/package/sass-mq) in my Nuxt project. Here is my code:
```scss
// src/assets/styles/mq.scss
@use '~sass-mq' as *;
// or, @use '../../../node_modules/sass-mq' as *;
// I tried both, but neither of them succeeded.
```
```ts
// nuxt.config.ts
modules: [
  '@/modules/style-resources'
],
styleResources: {
  scss: ['assets/styles/mq.scss']
}
```
```scss
// src/pages/index.vue
.hoge {
  @include mq($from mobile) {/* */}
}
```
It says `Undefined mixin`.

**Comment by inomata137** [comment]
I was just stupid.
This worked:
```ts
- additionalData: '@import "@/assets/scss/global.scss";',
+ additionalData: '@use "path/to/file.scss" as *;',
```

**Comment by Camiloruiiz** [comment]
> I was just stupid. This worked:
> 
> ```ts
> - additionalData: '@import "@/assets/scss/global.scss";',
> + additionalData: '@use "path/to/file.scss" as *;',
> ```
[stackoverflow](https://stackoverflow.com/questions/70547375/global-sass-import-usage-nuxt-3-static-assets)

**Comment by wattanx** [comment]
I have created a `style-resources-module` for Nuxt 3. (It doesn't support Bridge yet, though.)
Please use it if you like.
https://github.com/wattanx/style-resources-module

**Comment by harlan-zw** [comment]
Will track Nuxt 3 support here https://github.com/nuxt-community/style-resources-module/issues/213 :)
