### ISSUE TITLE
Update docs for Nuxt 3

### ISSUE THREAD

**Issue by Llcoolsouder** [nuxt-community/style-resources-module#209]
The following is not clear from the documentation in the README.
1. Is this package compatible with Nuxt**3**?
2. If so, how do you configure your project to use this package?

The following SO post makes it appear that Nuxt3 is **not** supported and makes it clear that many devs are looking for this information. 
https://stackoverflow.com/a/70273538/6190865

I'm happy to update the docs myself, if someone more familiar with the package can confirm that this is the case.

**Comment by wattanx** [comment]
I have created a `style-resources-module` for Nuxt 3. (It doesn't support Bridge yet, though.)
Please use it if you like.
https://github.com/wattanx/style-resources-module

**Comment by harlan-zw** [comment]
Have updated the docs and made an issue to track here https://github.com/nuxt-community/style-resources-module/issues/213
