### ISSUE TITLE
Nuxt 3 Support

### ISSUE THREAD

**Issue by harlan-zw** [nuxt-community/style-resources-module#213]
Hey :wave: It looks like this module hasn't been updated for Nuxt 3. In an effort to improve the developer experience of modules, I've updated the module to clarify that it only supports Nuxt 2.

If Nuxt 3 support is added it will be moved to the https://github.com/nuxt-modules organisation.

Alternatives:
- https://github.com/wattanx/style-resources-module
- https://github.com/nuxt-community/style-resources-module/issues/190#issuecomment-956128536

@manniL  Is Nuxt 3 support something you have planned? If not, perhaps we can deprecate this module.

Please let us know and thanks for your work!

**Comment by manniL** [comment]
I'm more than happy to join efforts with @wattanx's module 👍

**Comment by wattanx** [comment]
Thanks!
I have confirmed that my module works with Nuxt 3, so it should be easy to create a PR 😄

**Comment by manniL** [comment]
@wattanx Awesome! A PR here would be much appreciated 🙏

**Comment by adamskeeled** [comment]
@wattanx Thanks for working on this 🙏 

I've started working on migrating my companies Nuxt 2 projects to Nuxt 3
@manniL Any predictions on when this can go live?

**Comment by manniL** [comment]
v2 has been released! Thanks a lot to @wattanx for the effort and work 🙏
