### ISSUE TITLE
Nuxt-Bridge support

### ISSUE THREAD

**Issue by yanniznik** [nuxt-community/style-resources-module#215]
Hi!
Is there any plan to have it work for `nuxt-bridge` with a `defineNuxtConfig` setup in `nuxt.config.ts`? Thank you!

**Comment by wattanx** [comment]
If you don't use Vite `@nuxtjs/style-resources@^1` will work.

When using Vite, the same can be done with the following options
https://vitejs.dev/config/shared-options.html#css-preprocessoroptions
