### ISSUE TITLE
Does this work anymore? Nuxt 3

### ISSUE THREAD

**Issue by CHEWX** [nuxt-community/style-resources-module#220]
Cannot get a simple setup to work so having to use this workaround for now:

https://github.com/nuxt/nuxt/issues/13690#issuecomment-1397312009

My setup:

nuxt.config.js

```
export default defineNuxtConfig({
  	buildModules: ['@nuxtjs/style-resources',],

	styleResources: {
    	        scss: [
      		        '~assets/scss/_mixins.scss'
    	        ]
  	}
})
```

`"@nuxtjs/style-resources": "^2.0.0",`

**Comment by wattanx** [comment]
Sorry, the README is wrong.
Nuxt 3 does not have buildModules.
Use the `modules` option instead.

**Comment by wattanx** [comment]
@tibineagu 
`@nuxtjs/style-resources` only supports webpack.

If you want to achieve the same thing with vite, use the following options
https://vitejs.dev/config/shared-options.html#css-preprocessoroptions

**Comment by tibineagu** [comment]
@wattanx thanks for the clarification. i implemented the preprocessorOptions and it works decently well.

Thank you!
