### ISSUE TITLE
Incompatible with Nuxt@2.4.0

### ISSUE THREAD

**Issue by DreaMinder** [nuxt-community/style-resources-module#23]
Returns an error on build time
```
This relative module was not found:                                       
* ./default.vue?vue&type=style&index=1&lang=scss& in ./layouts/default.vue   
```

If style block in layout removed - it just repeats the error for any vue-file that has scss in it.

config:
```
  styleResources: { scss: '@/assets/variables.scss' },
```

**Comment by manniL** [comment]
Very interesting. 

Can you provide a reproduction CodeSandbox by any chance?

**Comment by DreaMinder** [comment]
>Do you have extractCSS enabled?
no

https://codesandbox.io/s/92j18x4n2r

**Comment by manniL** [comment]
You still need `sass-loader` and `node-sass` in your deps.

With them, your example works fine for me.

**Comment by DreaMinder** [comment]
@manniL yes, sorry, I've failed with reproduction, but the issue was in dependencies

funny thing, I flushed them 2 times today but only on 3rd time it worked

**Comment by manniL** [comment]
Strange 🙈 

Does the initial bug still exist?

**Comment by DreaMinder** [comment]
@manniL no, thanks for assistance

**Comment by nuria-fl** [comment]
I ran into the same issue. Before I was using `nuxt-sass-resources-loader`, so when I upgraded to Nuxt 2.4 I switched to `@nuxtjs/style-resources`. For some reason, it breaks when I remove the old `nuxt-sass-resources-loader` dependency.

Maybe it's related to the `sass-resources-loader` dependency? `nuxt-sass-resources-loader` required `^1.3.1` version, while `@nuxtjs/style-resources` requires `^2.0.0`.

**Comment by manniL** [comment]
@nuria-fl make sure to update your deps after changing ☺️

**Comment by nuria-fl** [comment]
@manniL Yeah I did, still breaking 😕

**Comment by DreaMinder** [comment]
@nuria-fl try to delete package-lock, node_modules and run `npm i`

**Comment by clemator** [comment]
I had the same issue on my project with Nuxt 2.4.3, migrating from `nuxt-sass-resources-loader` to `@nuxtjs/style-resources`. After switching, it did not parse correctly all the `lang="scss"` attribute inside every `<style>` tags.
I resolve the issue by installing a new npm package: `sass-resources-loader`.
I also added to my `nuxt.config.js` the required property
```javascript
module.exports = {
...
  styleResources: {
   // your settings here
   scss: ['~/assets/scss/main.scss']
  },
...
}
```

**Comment by envision** [comment]
Having this same issue, using nuxt-ts-edge ^2.5.0-25858087.f39205a7
