### ISSUE TITLE
How to import SCSS files from node modules?

### ISSUE THREAD

**Issue by davision** [nuxt-community/style-resources-module#25]
Does this library support resource from node_modules? For example Foundation framework. Specifying it like this:

```
  styleResources: {
    scss: [
      'foundation-sites/scss/foundation.scss',
    ]
  },
```

does not work.

**Comment by davision** [comment]
Ok, I see, it works like this: `'./node_modules/foundation-sites/scss/foundation.scss',`

**Comment by manniL** [comment]
@davision The example you provide works now as well ☺️ (v0.1.2)

**Comment by davision** [comment]
O nice! Even more awesome!

**Comment by davision** [comment]
Just tried it out, but seems to not work. How exatcly should scss files from node_modules be imported?

**Comment by manniL** [comment]
@davision As in https://github.com/nuxt-community/style-resources-module/pull/31/files ☺️ 

Not sure if that works with files "inside" a module though 🤔
