### ISSUE TITLE
scss/sass resources from node_modules

### ISSUE THREAD

**Issue by SnO2WMaN** [nuxt-community/style-resources-module#30]
(Related #25)

When importing scss/sass library like [mathsass](https://github.com/terkel/mathsass).

It works in [style-resources-module](https://github.com/nuxt-community/style-resources-module),

```js
srcDir: 'src',
styleResources: {
	scss: [
		'~/../node_modules/mathsass/dist/_math.scss'
	]
},
```

and it don't.

```js
srcDir: 'src',
styleResources: {
	scss: ['mathsass']
},
```
But does below one seem to be more smarter? ([nuxt-sass-resources-loader](https://github.com/anteriovieira/nuxt-sass-resources-loader) could.)

**Comment by blowsie** [comment]
I ran into a similar issue with bootstrap sass,
I had to import it like so;

```
  styleResources:{
    scss: [
      '~/assets/styles/_vars.scss',
      '~/../node_modules/bootstrap-sass/assets/stylesheets/_bootstrap.scss'
    ]
  },
```

**Comment by manniL** [comment]
That's strange. It should work with "just `bootstrap-sass/assets/stylesheets/_bootstrap.scss`"

**Comment by blowsie** [comment]
I'll try it, but in hindsight I think importing an entire library using the `style-resources-module` is not ideal anyway, I should only be importing the `mixins` and `variables`, other wise the components css is being imported for every component right?

**Comment by manniL** [comment]
@blowsie Correct! Only add **variables**, **mixins** and so on. Everything that "vanishes" in the end.

However, there are "utility-only" SASS/SCSS libs like `mathsass` where this makes sense.

**Comment by manniL** [comment]
Any update on it? Can somebody repro the issue?

**Comment by blowsie** [comment]
I'm happy to close, `bootstrap-sass/assets/stylesheets/_bootstrap.scss` worked

**Comment by PawelGIX** [comment]
But this not work for me:
@import "bootstrap/scss/_functions.scss";
@import "bootstrap/scss/_variables.scss";
@import "bootstrap/scss/_mixins.scss";

I get error 
`Module build failed (from ./node_modules/sass-loader/dist/cjs.js): SassError: File to import not found or unreadable: ../../scss/bootstrap/scss/_functions.scss. on line 16 of E:\Ampps\www\cash_your_gift\assets\scss\app.scss >> @import "../../scss/bootstrap/scss/_functions.scss";`

How import something from node_modules inside *.scss file loaded with style-resources-module?
