### ISSUE TITLE
Duplication of styles as components grow

### ISSUE THREAD

**Issue by Loschcode** [nuxt-community/style-resources-module#35]
I actually faced the problem of @import working on a NuxtJS project and ended up asking Stackoveflow. I then found your library which's a great idea, I thought this would be the solution but the problem remains the same...

When you use your loader, for each component present on the page it'll duplicate the styling on the page, and it'll be visible on the chrome developer tools as referred here https://stackoverflow.com/questions/54793275/global-styling-vs-local-styling-in-vuejs

Is there a way to load the SCSS on top of something and avoid this duplication ? It makes the page way heavier in development...

Thanks

PS: the problem is bigger than what we could think, it confuses the order of the rules in CSS because it loads it from everywhere at random time, so you can hardly make any shared logic at some point ...

**Comment by manniL** [comment]
**Don't styles**. Inject only variables.

You can't avoid that styles will leak into all components otherwise :|

**Comment by EvilJimJafar** [comment]
Can you explain what you mean by this @manniL ?

Is this causing the duplication?

`@include border-radius(1em); `
