### ISSUE TITLE
Takes a minute to process reloads

### ISSUE THREAD

**Issue by dant672** [nuxt-community/style-resources-module#36]

**Comment by dant672** [comment]
Hi there i have the following setup:

`require('dotenv').config()

import drInfo from './assets/json/drInfo';
import blogs from './static/json/articles';
const baseUrl = process.env.NODE_ENV === 'production' ? process.env.BASE_URL : 'http://localhost:3000/'

//console.log(drInfo);
console.log(blogs);
console.log(drInfo);


module.exports = {
  /*
  ** Headers of the page
  */

  plugins: ['~/plugins/vue-social-sharing',],

  modules: [
    // provide path to the file with resources
    'bootstrap-vue/nuxt', '@nuxtjs/dotenv', '@nuxtjs/google-analytics', '@nuxtjs/style-resources',
  ],
  styleResources: {
    scss: [
      './style.scss', './static/scss/*.scss' // use underscore "_" & also file extension ".scss"
      ]
  },
  env: {
    baseUrl : baseUrl,
  },



  /*
  ** Customize the progress bar color
  */
  loading: { color: '#3B8070' },

  
  generate: {
    routes: function(){
      let articles = blogs.map((article) => {
        return {
          route: '/blog/' + article.slug,
          payload: article
        }
      });
      let conditions = drInfo.conditions.map((condition) => {
        return {
          route: '/services/' + condition.path,
          payload : condition
        }
      })
      let videos = drInfo.videos.map((video) => {
        return {
          route: '/videos/' + video.url_path,
          payload: video
        }
      })
      console.log(conditions);
      return[...articles, ...conditions, ...videos]
    } 
  },
  /*
  ** Build configuration
  */
  build: {
    /*
    ** Run ESLint on save
    */
    extend (config, { isDev, isClient }) {
      if (isDev && isClient) {
        config.module.rules.push({
          enforce: 'pre',
          test: /\.(js|vue)$/,
          loader: 'eslint-loader',
          exclude: /(node_modules)/
        })
      }
    }
  }
}`

**Comment by manniL** [comment]
That *can* happen as SCSS is injected into every single component which uses SASS. That's why you should only include variables (and mixins and so on) as well.

You can boost the build time with some experimental features I guess, see https://github.com/nuxt/nuxt.js/issues/5131
