### ISSUE TITLE
Variables accessible in components

### ISSUE THREAD

**Issue by jeckojim** [nuxt-community/style-resources-module#46]
Hi,

I'm using Nuxt with Bulma with Buefy and I would like to import only the Bulma components where I need it, but I got an error when import the scss component in a vue/nuxt components even if I added the style-resources-module and the variables and utilities files. Is it possible to do it or I misunderstood the capacity of this module.

My nuxt config file: 

```
'@nuxtjs/style-resources',
    ['nuxt-buefy', {
      css: false
    }]
    
  ],
  
  styleResources: {
    scss: [
      './assets/vars/*.scss',
      './assets/custom-styles.scss',
      './assets/abstracts/_mixins.scss'
    ]
  },
```

 my assets/vars/init.scss:
```
// Set your brand colors
$black: #272322;
$white: #FFFFFF;

// Update Bulma's global variables
$family-sans-serif: "Heebo", sans-serif;
$link: $white;

// Update some of Bulma's component variables
$body-background-color: $black;
$body-color: $white;
$control-border-width: 1px;
```

my custom-styles.scss:
```
@import "~bulma/sass/utilities/_all";
@import "~bulma/sass/base/_all";
```

and finally my TheNavbar.vue component:

```
<style lang="scss" scoped>
@import "~/node_modules/bulma/sass/components/navbar.sass";
</style>
```

I got an error that says $background is not defined, but it is in the Bulma utilities files. I was thinking that style-resource-modules exposed the variables without the need to import it every where I want to use it.

Thank you

**Comment by jeckojim** [comment]
I found it, simply needed to refer correctly the path:

```
scss: [
      '**~/**assets/vars/*.scss',
      '**~/**assets/custom-styles.scss',
      '**~/**assets/abstracts/_mixins.scss'
    ]
```

**Comment by manniL** [comment]
Glad u solved it :relaxed:

**Comment by jeckojim** [comment]
Just to help someone else, I discovered that adding `@import "~bulma/sass/utilities/_all";` resulted with repeated styles because of the `~bulma/sass/utilities/animations` that is imported in the utilities `_all.sass` file and containing rules and not just variables or mixins.

I fixed it by importing animations file appart in global css file:

My nuxt config file:
```
...
/*
  ** Global CSS
  */
  css: [
    './assets/custom-styles.scss'
  ],
  modules: [
  ...
  '@nuxtjs/style-resources',
  ...
  ],
  styleResources: {
    scss: [
      '~assets/vars/*.scss',
      '~assets/abstracts/_mixins.scss'
    ]
  },
...
```

my  `assets/vars/variables.scss`,

```
@import "~bulma/sass/utilities/initial-variables";
@import "~bulma/sass/utilities/functions";
@import "~bulma/sass/utilities/derived-variables";
@import "~bulma/sass/utilities/mixins";
@import "~bulma/sass/utilities/controls";
// Set your brand colors
$black: #272322;
$white: #FFFFFF;

// Update Bulma's global variables
$family-sans-serif: "Heebo", sans-serif;
$link: $white;

// Update some of Bulma's component variables
$body-background-color: $black;
$body-color: $white;
$control-border-width: 1px;
...
```

my `custom-styles.scss`:
```
@import "~bulma/sass/utilities/animations";
@import "~bulma/sass/base/_all";
```

Hope it can help someone.
