### ISSUE TITLE
Very slow scss compilation problem.

### ISSUE THREAD

**Issue by selimdoyranli** [nuxt-community/style-resources-module#65]
My nuxt.config.js (Nuxt: 2.8.1)

    import pkg from './package'
    
    export default {
      mode: 'universal',
    
      /*
      ** Headers of the page
      */
      head: {
        title: pkg.name,
        meta: [
          { charset: 'utf-8' },
          { name: 'viewport', content: 'width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' },
          { hid: 'description', name: 'description', content: pkg.description }
        ],
        link: [
          { rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' }
        ]
      },
    
      /*
      ** Customize the progress-bar color
      */
      loading: { color: '#012353' },
    
      /*
      ** Global CSS
      */
      css: [
        // External CSS Libs
        '~/assets/css/libs/animate.css'
      ],
    
      /*
      ** Plugins to load before mounting the App
      */
      plugins: [
        { src: '~/plugins/vue-masonry', ssr: false },
        { src: '~/plugins/vue-rellax', ssr: false },
        { src: '~/plugins/vue-simplebar'}
      ],
    
      /*
      ** Nuxt.js modules
      */
      modules: [
        '@nuxtjs/style-resources',
        // Doc: https://bootstrap-vue.js.org/docs/
        'bootstrap-vue/nuxt',
        '@nuxtjs/axios',
      ],
    
      /*
      ** SCSS Global 
      */
      styleResources: {
        scss: [
          // App Global SCSS
          '~/assets/scss/app.scss'
          ]
      },
    
      /*
      ** Axios Config
      */
      axios: {
        // proxyHeaders: false
      },
    
      /*
      ** Build configuration
      */
      build: {
        /*
        ** You can extend webpack config here
        */
        extend(config, ctx) {
        }
      }
    }

My package.json

    ...
      "private": true,
      "scripts": {
        "dev": "nuxt",
        "build": "nuxt build",
        "start": "nuxt start",
        "generate": "nuxt generate",
        "json:server": "json-server --watch ./static/json/db.json --port 3004 --read-only --delay 1000",
        "now-build": "nuxt generate"
      },
      "dependencies": {
        "@nuxtjs/axios": "5.5.4",
        "bootstrap": "4.1.3",
        "bootstrap-vue": "2.0.0-rc.26",
        "cross-env": "^5.2.0",
        "nuxt": "2.8.1",
        "swiper": "4.5.0",
        "vue-content-loading": "1.6.0",
        "vue-masonry": "0.11.7",
        "vue-rellax": "0.1.0",
        "vue-simplebar": "1.0.0"
      },
      "devDependencies": {
        "@nuxtjs/style-resources": "0.1.2",
        "node-sass": "4.11.0",
        "nodemon": "1.18.9",
        "pug": "2.0.3",
        "pug-plain-loader": "1.0.0",
        "sass-loader": "7.1.0"
      }
    }

My app.scss

    // utilities
    @import 'utilities/browserhack';
    @import 'utilities/variables';
    @import 'utilities/mixins';
    @import 'utilities/general';
    @import 'utilities/extra';
    
    // shared
    @import 'shared/lab-elements';
    @import 'shared/layout';

**When I make changes to any imported file, the scss compilation takes 20-25 seconds.**

Why?

#### Related Video:
[https://www.loom.com/share/ce936ad5cac047f8bbdb60c1d293e391](https://www.loom.com/share/ce936ad5cac047f8bbdb60c1d293e391)

**Comment by manniL** [comment]
> Important notice: Do not import actual styles. Use this module only to import variables, mixins, functions (et cetera) as they won't exist in the actual build. Importing actual styles will include them in every component and will also make your build/HMR magnitudes slower. Do not do this!

**Comment by HugoHeneault** [comment]
Hello, 

I've got the same kind of problem. 
My base.scss file only contains variables & mixins. 

Here is my profile using `yarn dev --profile` on reload:

```
Profile results for Client

> Stats by Ext

Ext    Requests  Time  Time/Request  Description

scss   2         62ms  31ms          SASS files

vue    95        23s   245ms         Vue Single File components

Total  97        23s

> Stats by Loader

Loader                 Requests  Time  Time/Request  Description

css-loader             97        23s   240ms         Css-loader

postcss-loader         97        23s   240ms         Postcss-loader

sass-loader            97        23s   240ms         Sass-loader

sass-resources-loader  97        23s   240ms         Sass-resources-loader

vue-loader             190       46s   245ms         Vue-loader

Total                  578       2m


Profile results for Server

> Stats by Ext

Ext    Requests  Time  Time/Request  Description

scss   2         13ms  6ms           SASS files

vue    95        12s   125ms         Vue Single File components

Total  97        12s

> Stats by Loader

Loader                 Requests  Time  Time/Request  Description

css-loader             97        12s   122ms         Css-loader

postcss-loader         97        12s   122ms         Postcss-loader

sass-loader            97        12s   122ms         Sass-loader

sass-resources-loader  97        12s   122ms         Sass-resources-loader

vue-loader             190       24s   125ms         Vue-loader

Total                  578       1m

```

**Comment by octoduchilli** [comment]
@selimdoyranli Did you resolve your problem ?

**Comment by selimdoyranli** [comment]
@octoduchilli 


slightly faster than before but i think still it's not enough. structure of my project in this way:


nuxt.config.js

    /*
    
    ** Global Styles
    
    */
    
    styleResources: {
    
    scss: [
    
    // Utilities
    
    '~/assets/scss/utilities/_browserhack.scss', 
    
    '~/assets/scss/utilities/_variables.scss',
    
    '~/assets/scss/utilities/_mixins.scss'
    
    ]
    
    },
    
    /*
    
    ** Global Styles (App, Libs.)
    
    */
    
    css: [
    
    // App
    
    '~/assets/scss/app.scss',
    
    // External Libs
    
    '~/assets/css/libs/animate.css'
    
    ],
    
    /*


and app.scss
```
// shared
@import 'shared/lab-elements';
@import 'shared/layout';
```

app.scss moved to css array, only global styles for style resources scss array and i used "_" for style files

check for my example starter kit:

[https://github.com/RadKod/RKnuxtstarterkit](https://github.com/RadKod/RKnuxtstarterkit)

**Comment by GanchoDanailov** [comment]
Any update on this issue?
So slow compilation is just killing me :/

**Comment by simllll** [comment]
Experience also super slow build process:
> Stats by Loader
Loader                 Requests  Time   Time/Request  Description
babel-loader           1799      41s    23ms          Babel-loader
ts-loader              835       21s    25ms          Ts-loader
vue-loader             5992      14m    138ms         Vue-loader
vue-style-loader       382       361ms  945μs         Vue-style-loader
css-loader             1632      7m     242ms         Css-loader
postcss-loader         1632      7m     242ms         Postcss-loader
sass-loader            1581      7m     248ms         Sass-loader
**sass-resources-loader  1581      7m     248ms         Sass-resources-loader**
url-loader             122       3s     21ms          Url-loader
file-loader            80        2s     26ms          File-loader
vue-svg-loader         818       13s    16ms          Vue-svg-loader
less-loader            5         2s     310ms         Less-loader
Total                  16459     41m

Profile results for Server
> Stats by Ext
Ext    Requests  Time   Time/Request  Description
js     89        2s     18ms          JavaScript files
ts     303       3s     9ms           ts files
vue    3605      2m     40ms          Vue Single File components
**scss   180       2m     765ms         SASS files**
png    63        4s     60ms          png files
svg    863       2m     135ms         svg files
ttf    3         9ms    3ms           ttf files
woff   3         625μs  208μs         woff files
woff2  2         399μs  199μs         woff2 files
eot    4         152ms  38ms          eot files
Total  5115      7m

this wasn't the case some days ago, but couldn't nail it down to something specific :....

Total                  16152     26m

**Comment by simllll** [comment]
Update. turned out this was due to purgecss plugin... if you use postcss mode, look into the new "contentFunction" to gain major performance improvements.
still interested in why this is reported via "sass-resource-loader"...

**Comment by dcrabbeYapily** [comment]
hello - how did you config contentFunction?

**Comment by selimdoyranli** [comment]
> hello - how did you config contentFunction?

Hello,

I've overcome this problem. I write the actual styles (class names, borders, css propertys etc.) inside the vue files, it will work correctly even if there is a separate .scss file. Use Style Resources Module only for code to be compiled (mixins, sass functions). If you define actual style codes in Style Resources Module, they will slow down as they will be imported everywhere.

For sample project, please see: https://github.com/RadKod/rk-nuxt-atomic-design-starter
