### ISSUE TITLE
 File to import not found or unreadable: abstracts/functions.

### ISSUE THREAD

**Issue by Alfr3d** [nuxt-community/style-resources-module#66]
Hi people,

when I use attribute lang=...  in tag style the console generated this error:

Module build failed (from ./node_modules/sass-loader/lib/loader.js)....
 File to import not found or unreadable: abstracts/functions.
      in /.../components/Header.vue (line 4, column 1)

"@nuxtjs/style-resources": "^0.1.2",
"node-sass": "^4.12.0",
"sass-loader": "^7.1.0"

**Comment by manniL** [comment]
Please provide a reproduction repo or codesandbox.

**Comment by Alfr3d** [comment]
Hi @manniL ,

I found (probably) the issue. 
In my proj I've used many file scss imported in a single main file. That file cause the issue. 
I've used a wrong method for import singular scss file.
`@import 
'test.scss',
'test2.scss',
'test3.scss';`

instead of:
`@import 'test.scss';
@import 'test2.scss';
@import 'test3.scss';`

I think the problem is there. I've not that error on my console.

**Comment by manniL** [comment]
:+1:
