### ISSUE TITLE
Error! Build import SCSS for SASS files

### ISSUE THREAD

**Issue by MrJmpl3** [nuxt-community/style-resources-module#67]
I have the error:
"Semicolons aren't allowed in the indented syntax."

Config:

```js
styleResources: {
    scss: ['./assets/styles/vuetify/variables/_vuetify.scss'],
    less: [],
    stylus: []
  }
```

I think the problem is because , the module import to sass files too (I want the import too in sass files)

I fixed using the data option from sass-loader, but I wish use this module

**Comment by jessielaf** [comment]
I have the exact same error. https://github.com/nuxt-community/vuetify-module/issues/82 for more details.

**Comment by yariksav** [comment]
Have same problem

**Comment by hirayama** [comment]
I have same problem and find a bit of evidence when I use `@nuxtjs/vuetify@1.1.1`.

In `nuxt.config.js`, 

```js
  vuetify: {
    treeShake: true,
  }
...
  styleResources: {
    scss: ['~assets/some/variables.scss']
  }
```

This setting may cause `Semicolons aren't allowed in the indented syntax.`.
When a-la-carte mode is TRUE, it seems that `@nuxtjs/style-resources` module insert the text content of `varialbes.scss` also into `*.sass` file, and I inevitably get the error message, "Syntax Error".

**Comment by aaharu** [comment]
I have same problem. This changes looks working.
`lib/module.js`
```diff
@@ -52,7 +52,7 @@
   }
 
   if (sass.length) {
-    scss.push(...sass)
+    this.extendBuild(extendSass(sass))
   }
 
   if (scss.length) {
@@ -89,7 +89,8 @@
   })
 }
 
-const extendScss = extendWithSassResourcesLoader(/s[ac]ss/)
+const extendSass = extendWithSassResourcesLoader(/sass/)
+const extendScss = extendWithSassResourcesLoader(/scss/)
 const extendLess = extendWithSassResourcesLoader(/less/)
 
 module.exports.meta = require('../package.json')
```

**Comment by manniL** [comment]
So splitting up `scss` and `sass` works, alright.

I'd accept a (tested) PR introducing that feature. Either as a breaking change or with an optional flag.

**Comment by rwam** [comment]
Great findings @aaharu – Coming from https://github.com/nuxt-community/vuetify-module/issues/82 I've tested the code changes and get my build task running again.

Nice to see the changes merged!

**Comment by manniL** [comment]
Released v1

**Comment by rwam** [comment]
That was quite fast! Many thanks.
