### ISSUE TITLE
Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by MrWangjiahuan** [nuxt-community/style-resources-module#72]
Cannot read property 'forEach' of undefined

**Comment by manniL** [comment]
Please provide a more detailed error description :relaxed:

**Comment by chettapong** [comment]
> 
> 
> Please provide a more detailed error description ☺️

when added extend custom loader in nuxt.conf

```js
  build: {
    /*
     ** You can extend webpack config here
     */
    extend(config, ctx) {
      config.module.rules.push({
        test: /\.less$/,
        loader: 'less-loader',
        options: {
          javascriptEnabled: true
        }
      })
    }
  }
```

**Comment by manniL** [comment]
Nuxt is already using less-loader by default. Adding it again will cause the issue

Src: https://github.com/nuxt/nuxt.js/blob/c010addb34db2f41886236fcd89688d0a5cd0377/packages/webpack/src/config/base.js#L288-L292

you can configure the loader easily via `loaders`: https://nuxtjs.org/api/configuration-build#loaders
