### ISSUE TITLE
CSS Variables missing

### ISSUE THREAD

**Issue by IOIIOOIO** [nuxt-community/style-resources-module#73]
Hi, when I have CSS Variables imported as a partial SCSS file, it doesn't get compiled.

Here is my setup:

**nuxt.config.js**
```
export default {
  modules: ['@nuxtjs/style-resources'],
  styleResources: {
    scss: [
      './assets/styles/index.scss'
      ]
  }
}
```
**_root.scss**
```
:root { 
  // colors
  --brand: #D7E8BA;
  --brand-dark: #7F8C76;
  ...
}
```
**index.scss**
```
  ...
  @import "./root";
  ...
```

I'm fairly certain it has something to do with the `style-resources` module for two reasons:

[1] With `style-resources` still turned on, If I put a `:root` selector in the component and leave it empty then it compiles fine
eg: 
```
<style lang="scss">
  :root {}
</style>
```

[2] I turn `style-resources` off and simply import the SCSS file directly in the components style tag then it compiles fine.
eg:
```
<style lang="scss">
  @import "~/assets/styles/index";
</style>
```

At first, I thought it might be `purgecss` that was causing the issue - but even with `purgecss` turned off I still have the same issues.

**Comment by manniL** [comment]
> **Important notice: Do not import actual styles.**

This also applies to css variables. If you include `_root.scss` in your global CSS as usual, the variables should be there and also accessible.
