### ISSUE TITLE
 Doesn't work when building nuxt programmatically

### ISSUE THREAD

**Issue by moka491** [nuxt-community/style-resources-module#76]
When using one of the "use nuxt programmatically" examples from nuxt docs, the build will error out saying that variables and mixins are not found. (The ones defined in the scss files loaded by this module). When building the same project using yarn build, it works fine.

I created a sandbox based on template.nuxtjs.org that replicates this issue:
https://codesandbox.io/s/codesandbox-nuxt-l6kos

I changed the following things in the template:
- add styleresources module
- installed node-sass and sass-loader
- added style.scss in ./assets that contains a variable $variable
- made styleresources module import this style.scss automatically
- made index.vue use the $variable for coloring the NuxtJS in red.

I added a script inside package.json that builds the project programmatically (taken from nuxt docs). If you open codesandbox and run yarn build, it will run. If you run yarn buildnuxt (which calls the script), it will complain about the scss variable.
Both of these are accessible in code sandbox from the "server control panel" menu on the left.

**Comment by rchl** [comment]
Your reproduction has an error. You are exporting a function from `nuxt.config.js` instead of an object but treating it as an object in `nuxtBuild.js`.

**Comment by moka491** [comment]
Thank you very much! That was literally the issue haha.
Lack of ES6 support in node called scripts lead me to adjust the way the nuxt config was exported, and then it worked but scss threw an error. It makes sense that it doesn't work when the nuxt config can't be imported correctly, but how in the world were I supposed to debug that 😄
