### ISSUE TITLE
SCSS/Sass is not importing the files

### ISSUE THREAD

**Issue by samuells** [nuxt-community/style-resources-module#9]
Hi,

I have a issue with importing files in SCSS/Sass. It just doesn't import variables/mixins. Also I noticed that once it worked - but I can't repeat it. Basically it doesn't work at all.

This is `nuxt.config.js`
```js
  /*
  ** Nuxt.js modules
  */
  modules: ["@nuxtjs/style-resources"],

  /*
  ** Deafult SCSS Files import - requirments for all components
  */
  styleResources: {
    scss: ["./assets/scss/toolbelt"]
  },
```

My folder structure from root: 
<img width="290" alt="screenshot 2018-11-13 11 46 35" src="https://user-images.githubusercontent.com/5185019/48408514-cb042a00-e739-11e8-8da3-dab3e4aefddf.png">

And this is use of mixin/variable in `index.vue`
```scss
<style lang="scss" scoped>
.links {
  margin: rem(20);
  color: $black;
}
</style>
```

thx for any help - if this works - it's great help

**Comment by manniL** [comment]
Hey! Could you provide a minimal reproduction build? (Template: https://template.nuxtjs.org/)

My first guess would be that you'd have to use `_toolbelt` or `toolbelt.scss`.

**Comment by samuells** [comment]
Found a solution. It needs to be `"~assets/scss/_toolbelt.scss" `

`nuxt.config.js`
```
styleResources: {
    scss: ["~assets/scss/_toolbelt.scss"]
  },
```

Maybe you should update readme file with the sample .. or I could do it.

thx

**Comment by manniL** [comment]
`"~assets/scss/_toolbelt.scss"` and `"./assets/scss/_toolbelt.scss"` should both work fine!

**Comment by manniL** [comment]
Feel free to send in a PR if you think something is unclear in the docs ☺️ 

Closing this one as it's solved 👍
