### ISSUE TITLE
Short Syntax of declaring config doesn't work

### ISSUE THREAD

**Issue by sugoidesune** [nuxt-community/style-resources-module#93]
I wanted to declare the assets like so but it doesn't want to work. I tried all paths.

```
  [
    '@nuxtjs/style-resources', {
      scss: [ "~css/variables.scss"],
     }
  ]
```

It only works with this Syntax, could someone explain why or what im doing wrong?

```
  modules: ["@nuxtjs/style-resources"],

  styleResources: {
    scss: ["~css/variables.scss"]
  },
```

**Comment by sergiocerrutti** [comment]
I have the same problem, all modules work with that syntax but this.

**Comment by manniL** [comment]
Your chance to contribute! 😋

**Comment by manniL** [comment]
Probably resolved with the latest version
