### ISSUE TITLE
What's the difference between Global CSS and this?

### ISSUE THREAD

**Issue by webcoderkz** [nuxt-community/style-resources-module#96]
Nuxt has built-in global css property in nuxt.config.ts:

```
css: [
  {
    src: '@/assets/scss/file.scss',
    lang: 'scss'
  }
]
```

We can include actual styles using this property. Using `styleResources` we can globally inject variables, mixins, functions in to every component, but built-in `css` property does the same?

**Comment by cannap** [comment]
but you cant use variables in components without import the var/functions/mixins file each time in the component you want to use it

**Comment by manniL** [comment]
From the README:

---

**Warning:** Do not import actual styles. Use this module only to import variables, mixins, functions (et cetera) as they won't exist in the actual build. Importing actual styles will include them in every component and will also make your build/HMR magnitudes slower. Do not do this!

---

This module provides SCSS/LESS/Stylus variables for all components so you don't have to import the variables file manually everywhere. For adding global styles, `css` should be used ☺️
